## 1. Inspecting the dataset

In [18]:
import pandas as pd
import numpy as np

In [19]:
path = '../raw/'
dirty = pd.read_csv(path + 'dirty/census_income_kdd_dirty.csv')

In [20]:
dirty.head()

  ; age ;Class-Of-Worker;DETAILED INDUSTRY RECODE;detailed occupation recode;education; wage per hour ;Enroll-In-Edu-Inst-Last-Wk;MARITAL STAT;major industry code;major_occupation_code; race ;Hispanic-Origin;SEX;member of a labor union;reason_for_unemployment; full or part time employment stat ;Capital-Gains;CAPITAL LOSSES;dividends from stocks;tax_filer_stat; region of previous residence ;State-Of-Previous-Residence;DETAILED HOUSEHOLD AND FAMILY STAT;detailed household summary in household;instance_weight; migration code change in msa ;Migration-Code-Change-In-Reg;MIGRATION CODE MOVE WITHIN REG;live in this house 1 year ago;migration_prev_res_in_sunbelt; num persons worked for employer ;Family-Members-Under-18;COUNTRY OF BIRTH FATHER;country of birth mother;country_of_birth_self; citizenship ;Own-Business-Or-Self-Employed;FILL INC QUESTIONNAIRE FOR VETERAN ADMIN;veterans benefits;weeks_worked_in_year; year ;Income;SOURCE SPLIT
0  0;73; Not in universe;0;0; High school graduat...
1  1;58; Self-employed-not incorporated;4;34; Som...
2  2;18; Not in universe;0;0; 10th grade;0; High ...
3  3;9; Not in universe;0;0; Children;0; Not in u...
4  4;10; Not in universe;0;0; Children;0; Not in ...

In [21]:
dirty = pd.read_csv(path + 'dirty/census_income_kdd_dirty.csv', sep=';')

In [22]:
dirty.head()

,Unnamed: 0,age,Class-Of-Worker,DETAILED INDUSTRY RECODE,detailed occupation recode,education,wage per hour,Enroll-In-Edu-Inst-Last-Wk,MARITAL STAT,major industry code,...,country of birth mother,country_of_birth_self,citizenship,Own-Business-Or-Self-Employed,FILL INC QUESTIONNAIRE FOR VETERAN ADMIN,veterans benefits,weeks_worked_in_year,year,Income,SOURCE SPLIT
0,0,73,Not in universe,0,0,High school graduate,0,Not in universe,Widowed,Not in universe or children,...,United-States,United-States,Native- Born in the United States,0,Not in universe,2,0,95,- 50000.,train
1,1,58,Self-employed-not incorporated,4,34,Some college but no degree,0,Not in universe,Divorced,Construction,...,United-States,United-States,Native- Born in the United States,0,Not in universe,2,52,94,- 50000.,train
2,2,18,Not in universe,0,0,10th grade,0,High school,Never married,Not in universe or children,...,Vietnam,Vietnam,Foreign born- Not a citizen of U S,0,Not in universe,2,0,95,- 50000.,train
3,3,9,Not in universe,0,0,Children,0,Not in universe,Never married,Not in universe or children,...,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.,train
4,4,10,Not in universe,0,0,Children,0,Not in universe,unknown,unknown,...,United-States,United-States,Native- Born in the United States,0,Not in universe,0,0,94,- 50000.,train

In [23]:
dirty.columns

Index(['Unnamed: 0', ' age ', 'Class-Of-Worker', 'DETAILED INDUSTRY RECODE',
       'detailed occupation recode', 'education', ' wage per hour ',
       'Enroll-In-Edu-Inst-Last-Wk', 'MARITAL STAT', 'major industry code',
       'major_occupation_code', ' race ', 'Hispanic-Origin', 'SEX',
       'member of a labor union', 'reason_for_unemployment',
       ' full or part time employment stat ', 'Capital-Gains',
       'CAPITAL LOSSES', 'dividends from stocks', 'tax_filer_stat',
       ' region of previous residence ', 'State-Of-Previous-Residence',
       'DETAILED HOUSEHOLD AND FAMILY STAT',
       'detailed household summary in household', 'instance_weight',
       ' migration code change in msa ', 'Migration-Code-Change-In-Reg',
       'MIGRATION CODE MOVE WITHIN REG', 'live in this house 1 year ago',
       'migration_prev_res_in_sunbelt', ' num persons worked for employer ',
       'Family-Members-Under-18', 'COUNTRY OF BIRTH FATHER',
       'country of birth mother', 'country_of_birth_self', ' citizenship ',
       'Own-Business-Or-Self-Employed',
       'FILL INC QUESTIONNAIRE FOR VETERAN ADMIN', 'veterans benefits',
       'weeks_worked_in_year', ' year ', 'Income', 'SOURCE SPLIT'],
      dtype='str')

In [24]:
dirty.drop(columns=['Unnamed: 0'], inplace=True)

In [25]:
dirty.shape

(299288, 43)

In [26]:
dirty.info()

<class 'pandas.DataFrame'>
RangeIndex: 299288 entries, 0 to 299287
Data columns (total 43 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0    age                                      296332 non-null  str
 1   Class-Of-Worker                           296296 non-null  str
 2   DETAILED INDUSTRY RECODE                  296296 non-null  str
 3   detailed occupation recode                299288 non-null  int64
 4   education                                 296296 non-null  str
 5    wage per hour                            299288 non-null  str
 6   Enroll-In-Edu-Inst-Last-Wk                299288 non-null  str
 7   MARITAL STAT                              296296 non-null  str
 8   major industry code                       296296 non-null  str
 9   major_occupation_code                     299288 non-null  str
 10   race                                     296296 non-null  str
 11  Hispanic-Origin                           299288 non-null  str
 12  SEX                                       296295 non-null  str
 13  member of a labor union                   299288 non-null  str
 14  reason_for_unemployment                   296296 non-null  str
 15   full or part time employment stat        299288 non-null  str
 16  Capital-Gains                             299288 non-null  str
 17  CAPITAL LOSSES                            299288 non-null  int64
 18  dividends from stocks                     299288 non-null  int64
 19  tax_filer_stat                            296296 non-null  str
 20   region of previous residence             299288 non-null  str
 21  State-Of-Previous-Residence               299288 non-null  str
 22  DETAILED HOUSEHOLD AND FAMILY STAT        299288 non-null  str
 23  detailed household summary in household   299288 non-null  str
 24  instance_weight                           299288 non-null  float64
 25   migration code change in msa             299288 non-null  str
 26  Migration-Code-Change-In-Reg              299288 non-null  str
 27  MIGRATION CODE MOVE WITHIN REG            299288 non-null  str
 28  live in this house 1 year ago             299288 non-null  str
 29  migration_prev_res_in_sunbelt             299288 non-null  str
 30   num persons worked for employer          299288 non-null  int64
 31  Family-Members-Under-18                   299288 non-null  str
 32  COUNTRY OF BIRTH FATHER                   299288 non-null  str
 33  country of birth mother                   299288 non-null  str
 34  country_of_birth_self                     299288 non-null  str
 35   citizenship                              296296 non-null  str
 36  Own-Business-Or-Self-Employed             299288 non-null  int64
 37  FILL INC QUESTIONNAIRE FOR VETERAN ADMIN  299288 non-null  str
 38  veterans benefits                         299288 non-null  int64
 39  weeks_worked_in_year                      299288 non-null  str
 40   year                                     299288 non-null  int64
 41  Income                                    296296 non-null  str
 42  SOURCE SPLIT                              296296 non-null  str
dtypes: float64(1), int64(7), str(35)
memory usage: 98.2 MB

In [27]:
dirty.describe()

,detailed occupation recode,CAPITAL LOSSES,dividends from stocks,instance_weight,num persons worked for employer,Own-Business-Or-Self-Employed,veterans benefits,year
count,299288.000000,299288.000000,299288.000000,299288.000000,299288.000000,299288.000000,299288.000000,299288.000000
mean,11.314744,36.848641,195.849296,1740.096197,1.956156,0.176459,1.516502,94.506469
std,14.455996,269.788444,1937.837469,994.141051,2.364851,0.555238,0.850392,3.573081
min,0.000000,0.000000,0.000000,37.870000,0.000000,0.000000,0.000000,94.000000
25%,0.000000,0.000000,0.000000,1060.490000,0.000000,0.000000,2.000000,94.000000
50%,0.000000,0.000000,0.000000,1617.100000,1.000000,0.000000,2.000000,95.000000
75%,26.000000,0.000000,0.000000,2188.110000,4.000000,0.000000,2.000000,95.000000
max,46.000000,4608.000000,99999.000000,18656.300000,6.000000,2.000000,2.000000,2030.000000

## 2. Data Cleaning

### 2.1 Standardize the column names

In [28]:
dirty.columns = [col.strip().lower().replace(' ', '_').replace('-','_') for col in dirty.columns]

In [29]:
dirty.columns

Index(['age', 'class_of_worker', 'detailed_industry_recode',
       'detailed_occupation_recode', 'education', 'wage_per_hour',
       'enroll_in_edu_inst_last_wk', 'marital_stat', 'major_industry_code',
       'major_occupation_code', 'race', 'hispanic_origin', 'sex',
       'member_of_a_labor_union', 'reason_for_unemployment',
       'full_or_part_time_employment_stat', 'capital_gains', 'capital_losses',
       'dividends_from_stocks', 'tax_filer_stat',
       'region_of_previous_residence', 'state_of_previous_residence',
       'detailed_household_and_family_stat',
       'detailed_household_summary_in_household', 'instance_weight',
       'migration_code_change_in_msa', 'migration_code_change_in_reg',
       'migration_code_move_within_reg', 'live_in_this_house_1_year_ago',
       'migration_prev_res_in_sunbelt', 'num_persons_worked_for_employer',
       'family_members_under_18', 'country_of_birth_father',
       'country_of_birth_mother', 'country_of_birth_self', 'citizenship',
       'own_business_or_self_employed',
       'fill_inc_questionnaire_for_veteran_admin', 'veterans_benefits',
       'weeks_worked_in_year', 'year', 'income', 'source_split'],
      dtype='str')

### 2.2 Categorical columns

In [30]:
categorical = dirty.select_dtypes(include='str').columns
categorical

Index(['age', 'class_of_worker', 'detailed_industry_recode', 'education',
       'wage_per_hour', 'enroll_in_edu_inst_last_wk', 'marital_stat',
       'major_industry_code', 'major_occupation_code', 'race',
       'hispanic_origin', 'sex', 'member_of_a_labor_union',
       'reason_for_unemployment', 'full_or_part_time_employment_stat',
       'capital_gains', 'tax_filer_stat', 'region_of_previous_residence',
       'state_of_previous_residence', 'detailed_household_and_family_stat',
       'detailed_household_summary_in_household',
       'migration_code_change_in_msa', 'migration_code_change_in_reg',
       'migration_code_move_within_reg', 'live_in_this_house_1_year_ago',
       'migration_prev_res_in_sunbelt', 'family_members_under_18',
       'country_of_birth_father', 'country_of_birth_mother',
       'country_of_birth_self', 'citizenship',
       'fill_inc_questionnaire_for_veteran_admin', 'weeks_worked_in_year',
       'income', 'source_split'],
      dtype='str')

In [31]:
dirty.columns

Index(['age', 'class_of_worker', 'detailed_industry_recode',
       'detailed_occupation_recode', 'education', 'wage_per_hour',
       'enroll_in_edu_inst_last_wk', 'marital_stat', 'major_industry_code',
       'major_occupation_code', 'race', 'hispanic_origin', 'sex',
       'member_of_a_labor_union', 'reason_for_unemployment',
       'full_or_part_time_employment_stat', 'capital_gains', 'capital_losses',
       'dividends_from_stocks', 'tax_filer_stat',
       'region_of_previous_residence', 'state_of_previous_residence',
       'detailed_household_and_family_stat',
       'detailed_household_summary_in_household', 'instance_weight',
       'migration_code_change_in_msa', 'migration_code_change_in_reg',
       'migration_code_move_within_reg', 'live_in_this_house_1_year_ago',
       'migration_prev_res_in_sunbelt', 'num_persons_worked_for_employer',
       'family_members_under_18', 'country_of_birth_father',
       'country_of_birth_mother', 'country_of_birth_self', 'citizenship',
       'own_business_or_self_employed',
       'fill_inc_questionnaire_for_veteran_admin', 'veterans_benefits',
       'weeks_worked_in_year', 'year', 'income', 'source_split'],
      dtype='str')

#### Categorical columns to numeric

In [32]:
categorical_to_numeric = ['age','detailed_industry_recode','wage_per_hour','capital_gains', 'weeks_worked_in_year']

In [33]:
dirty[categorical] = dirty[categorical].fillna('NaN') #para nao dar erro no split

In [34]:
for col in categorical_to_numeric:
    dirty[col] = [n.split(sep=' ')[0] for n in dirty[col]]

In [35]:
for col in list(categorical_to_numeric):
    print(col, '\n', dirty[col].unique(), end='\n\n')

age
 <StringArray>
[  '73',   '58',   '18',    '9',   '10',   '48',   '42',   '28',   '47',
   '34',
 ...
 '80.0', '70.0', '88.0', '84.0', '68.0', '85.0', '89.0', '82.0', '79.0',
  '150']
Length: 191, dtype: str

detailed_industry_recode
 <StringArray>
[      '0',       '4',      '40',      '34',      '43',      '37',      '24',
      '39',      '12',      '35',      '45',       '3',      '19',      '29',
      '32',     'NaN',      '33',      '23',      '44',      '36',      '31',
      '30',      '41',        '',       '5',      '11',       '9',      '42',
       '6',      '18',      '50',       '2',       '1',      '26',      '48',
      '47',      '16',      '14',      '22',      '17',       '7',       '8',
      '25',      '46', 'unknown',      '27',      '15',      '13',      '49',
      '38',      '21',      '28',      '20',      '51',      '10']
Length: 55, dtype: str

wage_per_hour
 <StringArray>
[   '0', '1200',  '876',     '',  '500',  '400',  '450',  '650',  '475',
 '1100',
 ...
  '178', '2487', '1128', '1139', '1545',  '929', '1469', '1536', '1267',
  '737']
Length: 1459, dtype: str

capital_gains
 <StringArray>
[      '0',    '5178',     '991',    '2829',    '3464',    '5556',    '7298',
   '15024',    '1831',    '3137',
 ...
    '1140', '25124.0',    '2227',    '8530', '10605.0',    '1639',  '4650.0',
  '4416.0',  '1055.0',  '4386.0']
Length: 161, dtype: str

weeks_worked_in_year
 <StringArray>
[   '0',   '52',   '30',   '49',   '32',   '15',   '38',   '48',    '9',
   '24',   '50',   '10',   '45',   '43',    '4',   '26',   '40',   '20',
    '6',   '12',   '51',    '1',    '8',   '39',   '13',   '16',   '34',
     '',   '14',   '36',   '44',   '22',  '0.0',   '41',   '46',   '28',
   '23',   '35',   '25',   '17',   '11',   '37',    '5', '52.0',   '42',
   '29',    '2',   '21',   '19',   '47',    '3', '24.0',   '27',    '7',
   '18', '28.0', '12.0',   '33', '16.0', '45.0', '40.0',  '9.0',   '31',
  '4.0', '50.0', '46.0',  '8.0', '26.0', '48.0', '18.0', '38.0',  '5.0',
 '30.0', '35.0', '20.0',  '1.0', '36.0',  '6.0', '51.0', '25.0', '32.0',
 '22.0', '14.0', '39.0',  '2.0', '44.0', '47.0', '49.0', '10.0',  '7.0',
 '13.0',   '80', '17.0', '15.0', '41.0', '34.0']
Length: 96, dtype: str

In [36]:
replacements_categorical_to_numeric = {
    'unknown' : np.nan,
    'NaN' : np.nan,
    '' : np.nan,
    '?' : np.nan
}

In [37]:
for col in categorical_to_numeric:
    dirty[col] = pd.to_numeric(dirty[col].replace(replacements_categorical_to_numeric), errors='coerce')

dirty[categorical_to_numeric].describe()

,age,detailed_industry_recode,wage_per_hour,capital_gains,weeks_worked_in_year
count,292203.000000,293303.000000,298166.000000,298166.000000,298166.000000
mean,34.542554,15.348486,55.098080,431.301010,23.179578
std,22.329121,18.054087,273.413379,4667.560456,24.404981
min,-2.000000,0.000000,-100.000000,0.000000,0.000000
25%,15.000000,0.000000,0.000000,0.000000,0.000000
50%,33.000000,0.000000,0.000000,0.000000,8.000000
75%,50.000000,33.000000,0.000000,0.000000,52.000000
max,150.000000,51.000000,9999.000000,99999.000000,80.000000

#### Replacing values

In [38]:
replacements_categorical = {
    'NaN' : np.nan,
    ' ?' : np.nan,
    'unknown' : np.nan,
    'na' : np.nan
}

In [39]:
for col in list(dirty.select_dtypes('str').columns):
    dirty[col] = dirty[col].replace(replacements_categorical).str.strip().str.lower().str.replace(r'[\s-]+', '_', regex=True)
    print(col, '\n', dirty[col].unique(), end='\n\n')

class_of_worker
 <StringArray>
[               'not_in_universe', 'self_employed_not_incorporated',
                        'private',               'local_government',
                              nan,             'federal_government',
     'self_employed_incorporated',               'state_government',
          'self_employed_not_inc',                   'never_worked',
                    'without_pay']
Length: 11, dtype: str

education
 <StringArray>
[                  'high_school_graduate',
             'some_college_but_no_degree',
                             '10th_grade',
                               'children',
             'bachelors_degree(ba_ab_bs)',
                                      nan,
 'masters_degree(ma_ms_meng_med_msw_mba)',
                    'less_than_1st_grade',
     'associates_degree_academic_program',
                      '7th_and_8th_grade',
                                'hs_grad',
                             'bachelor's',
                  '12th_grade_no_diploma',
    'associates_degree_occup_/vocational',
 'prof_school_degree_(md_dds_dvm_llb_jd)',
                       '5th_or_6th_grade',
                             '11th_grade',
              'doctorate_degree(phd_edd)',
                              '9th_grade',
               '1st_2nd_3rd_or_4th_grade',
                              'bachelors']
Length: 21, dtype: str

enroll_in_edu_inst_last_wk
 <StringArray>
['not_in_universe', 'high_school', 'college_or_university']
Length: 3, dtype: str

marital_stat
 <StringArray>
[                        'widowed',                        'divorced',
                   'never_married',                               nan,
 'married_civilian_spouse_present',                       'separated',
           'married_spouse_absent',      'married_a_f_spouse_present']
Length: 8, dtype: str

major_industry_code
 <StringArray>
[        'not_in_universe_or_children',                        'construction',
                                   nan,                       'entertainment',
   'finance_insurance_and_real_estate',                           'education',
        'business_and_repair_services',      'manufacturing_nondurable_goods',
 'personal_services_except_private_hh',         'manufacturing_durable_goods',
         'other_professional_services',                              'mining',
                      'transportation',                     'wholesale_trade',
               'public_administration',                        'retail_trade',
                     'social_services',          'private_household_services',
     'utilities_and_sanitary_services',                      'communications',
                   'hospital_services',             'medical_except_hospital',
                         'agriculture',              'forestry_and_fisheries',
                        'armed_forces']
Length: 25, dtype: str

major_occupation_code
 <StringArray>
[                      'not_in_universe',
   'precision_production_craft_&_repair',
                'professional_specialty',
        'executive_admin_and_managerial',
           'handlers_equip_cleaners_etc',
        'adm_support_including_clerical',
 'machine_operators_assmblrs_&_inspctrs',
                         'other_service',
                                 'sales',
            'private_household_services',
       'technicians_and_related_support',
    'transportation_and_material_moving',
          'farming_forestry_and_fishing',
                   'protective_services',
                          'armed_forces']
Length: 15, dtype: str

race
 <StringArray>
[                      'white',   'asian_or_pacific_islander',
 'amer_indian_aleut_or_eskimo',                       'black',
                       'other',                           nan]
Length: 6, dtype: str

hispanic_origin
 <StringArray>
[                'all_other',               'do_not_know',
 'central_or_south_american',        'mexican_(mexicano)',
          'mexican_american',             'other_spanish',
              'puerto_rican',                     'cuban',
                   'chicano',                        'na']
Length: 10, dtype: str

sex
 <StringArray>
['female', nan, 'male', 'm', 'f']
Length: 5, dtype: str

member_of_a_labor_union
 <StringArray>
['not_in_universe', 'no', 'yes']
Length: 3, dtype: str

reason_for_unemployment
 <StringArray>
[    'not_in_universe', 'job_loser_on_layoff',                   nan,
     'other_job_loser',         'new_entrant',          're_entrant',
          'job_leaver']
Length: 7, dtype: str

full_or_part_time_employment_stat
 <StringArray>
[                'not_in_labor_force',           'children_or_armed_forces',
                'full_time_schedules',               'unemployed_full_time',
               'unemployed_part_time', 'pt_for_non_econ_reasons_usually_ft',
     'pt_for_econ_reasons_usually_pt',     'pt_for_econ_reasons_usually_ft']
Length: 8, dtype: str

tax_filer_stat
 <StringArray>
[                    'nonfiler',            'head_of_household',
          'joint_both_under_65',                       'single',
                            nan,               'joint_both_65+',
 'joint_one_under_65_&_one_65+']
Length: 7, dtype: str

region_of_previous_residence
 <StringArray>
['not_in_universe', 'south', 'northeast', 'midwest', 'west', 'abroad']
Length: 6, dtype: str

state_of_previous_residence
 <StringArray>
[     'not_in_universe',             'arkansas',                 'utah',
             'michigan',            'minnesota',               'alaska',
               'kansas',              'indiana',                    nan,
        'massachusetts',           'new_mexico',               'nevada',
            'tennessee',             'colorado',               'abroad',
             'kentucky',           'california',              'arizona',
       'north_carolina',          'connecticut',              'florida',
              'vermont',             'maryland',             'oklahoma',
               'oregon',                 'ohio',       'south_carolina',
                'texas',              'montana',              'wyoming',
              'georgia',         'pennsylvania',                 'iowa',
        'new_hampshire',             'missouri',              'alabama',
         'north_dakota',           'new_jersey',            'louisiana',
        'west_virginia',             'delaware',             'illinois',
                'maine',            'wisconsin',             'new_york',
                'idaho', 'district_of_columbia',         'south_dakota',
             'nebraska',             'virginia',          'mississippi']
Length: 51, dtype: str

detailed_household_and_family_stat
 <StringArray>
[       'other_rel_18+_ever_marr_not_in_subfamily',
                                     'householder',
         'child_18+_never_marr_not_in_a_subfamily',
           'child_<18_never_marr_not_in_subfamily',
                           'spouse_of_householder',
                            'secondary_individual',
       'other_rel_18+_never_marr_not_in_subfamily',
                           'nonfamily_householder',
      'grandchild_<18_never_marr_not_in_subfamily',
 'grandchild_<18_never_marr_child_of_subfamily_rp',
          'child_18+_ever_marr_not_in_a_subfamily',
            'child_18+_never_marr_rp_of_subfamily',
                'child_18+_spouse_of_subfamily_rp',
  'other_rel_<18_never_marr_child_of_subfamily_rp',
         'child_under_18_of_rp_of_unrel_subfamily',
      'grandchild_18+_never_marr_not_in_subfamily',
             'child_18+_ever_marr_rp_of_subfamily',
         'other_rel_18+_ever_marr_rp_of_subfamily',
                       'rp_of_unrelated_subfamily',
            'other_rel_18+_spouse_of_subfamily_rp',
       'other_rel_<18_never_marr_not_in_subfamily',
            'other_rel_<18_spouse_of_subfamily_rp',
                               'in_group_quarters',
           'grandchild_18+_spouse_of_subfamily_rp',
        'other_rel_18+_never_marr_rp_of_subfamily',
            'child_<18_never_marr_rp_of_subfamily',
            'child_<18_ever_marr_not_in_subfamily',
         'other_rel_<18_ever_marr_rp_of_subfamily',
       'grandchild_18+_ever_marr_not_in_subfamily',
                'child_<18_spouse_of_subfamily_rp',
             'spouse_of_rp_of_unrelated_subfamily',
     'other_rel_<18_never_married_rp_of_subfamily',
       'grandchild_18+_never_marr_rp_of_subfamily',
        'grandchild_18+_ever_marr_rp_of_subfamily',
             'child_<18_ever_marr_rp_of_subfamily',
        'other_rel_<18_ever_marr_not_in_subfamily',
       'grandchild_<18_never_marr_rp_of_subfamily',
       'grandchild_<18_ever_marr_not_in_subfamily']
Length: 38, dtype: str

detailed_household_summary_in_household
 <StringArray>
[      'other_relative_of_householder',                         'householder',
                   'child_18_or_older',        'child_under_18_never_married',
               'spouse_of_householder',          'nonrelative_of_householder',
 'group_quarters_secondary_individual',         'child_under_18_ever_married']
Length: 8, dtype: str

migration_code_change_in_msa
 <StringArray>
[               nan,       'msa_to_msa',         'nonmover',
 'nonmsa_to_nonmsa',  'not_in_universe', 'not_identifiable',
    'abroad_to_msa',    'msa_to_nonmsa', 'abroad_to_nonmsa',
    'nonmsa_to_msa']
Length: 10, dtype: str

migration_code_change_in_reg
 <StringArray>
[                             nan,                    'same_county',
                       'nonmover',               'different_region',
    'different_county_same_state',                'not_in_universe',
 'different_division_same_region',                         'abroad',
  'different_state_same_division']
Length: 9, dtype: str

migration_code_move_within_reg
 <StringArray>
[                           nan,                  'same_county',
                     'nonmover',     'different_state_in_south',
  'different_county_same_state',              'not_in_universe',
 'different_state_in_northeast',                       'abroad',
   'different_state_in_midwest',      'different_state_in_west']
Length: 10, dtype: str

live_in_this_house_1_year_ago
 <StringArray>
['not_in_universe_under_1_year_old', 'no', 'yes']
Length: 3, dtype: str

migration_prev_res_in_sunbelt
 <StringArray>
[nan, 'yes', 'not_in_universe', 'no']
Length: 4, dtype: str

family_members_under_18
 <StringArray>
[       'not_in_universe',   'both_parents_present',    'mother_only_present',
 'neither_parent_present',    'father_only_present']
Length: 5, dtype: str

country_of_birth_father
 <StringArray>
[               'united_states',                      'vietnam',
                  'philippines',                            nan,
                     'columbia',                      'germany',
                       'mexico',                        'japan',
                         'peru',           'dominican_republic',
                  'south_korea',                         'cuba',
                  'el_salvador',                       'canada',
                     'scotland', 'outlying_u_s_(guam_usvi_etc)',
                        'italy',                    'guatemala',
                      'ecuador',                  'puerto_rico',
                     'cambodia',                        'china',
                       'poland',                    'nicaragua',
                       'taiwan',                      'england',
                      'ireland',                      'hungary',
                   'yugoslavia',              'trinadad&tobago',
                      'jamaica',                     'honduras',
                     'portugal',                         'iran',
                       'france',                        'india',
                    'hong_kong',                        'haiti',
                       'greece',           'holand_netherlands',
                     'thailand',                         'laos',
                       'panama']
Length: 43, dtype: str

country_of_birth_mother
 <StringArray>
[               'united_states',                      'vietnam',
                            nan,                     'columbia',
                       'mexico',                  'el_salvador',
                         'peru',                  'puerto_rico',
                         'cuba',                  'philippines',
           'dominican_republic',                      'germany',
                      'england',                    'guatemala',
                     'scotland',                     'portugal',
                        'italy',                      'ecuador',
                   'yugoslavia',                        'china',
                       'poland',                      'hungary',
                    'nicaragua',                       'taiwan',
                      'ireland',                       'canada',
                  'south_korea',              'trinadad&tobago',
                      'jamaica',                     'honduras',
                         'iran',                       'france',
                     'cambodia',                        'india',
                    'hong_kong',                        'haiti',
                        'japan',                       'greece',
           'holand_netherlands',                     'thailand',
                       'panama',                         'laos',
 'outlying_u_s_(guam_usvi_etc)']
Length: 43, dtype: str

country_of_birth_self
 <StringArray>
[               'united_states',                      'vietnam',
                            nan,                     'columbia',
                       'mexico',                         'peru',
                         'cuba',                  'philippines',
           'dominican_republic',                  'el_salvador',
                       'canada',                     'scotland',
                     'portugal',                    'guatemala',
                      'ecuador',                      'germany',
 'outlying_u_s_(guam_usvi_etc)',                  'puerto_rico',
                        'italy',                        'china',
                       'poland',                    'nicaragua',
                       'taiwan',                      'england',
                      'ireland',                  'south_korea',
              'trinadad&tobago',                      'jamaica',
                     'honduras',                         'iran',
                      'hungary',                       'france',
                     'cambodia',                        'india',
                    'hong_kong',                        'japan',
                        'haiti',           'holand_netherlands',
                       'greece',                     'thailand',
                       'panama',                   'yugoslavia',
                         'laos']
Length: 43, dtype: str

citizenship
 <StringArray>
[          'native_born_in_the_united_states',
          'foreign_born_not_a_citizen_of_u_s',
                                          nan,
 'foreign_born_u_s_citizen_by_naturalization',
   'native_born_abroad_of_american_parent(s)',
 'native_born_in_puerto_rico_or_u_s_outlying']
Length: 6, dtype: str

fill_inc_questionnaire_for_veteran_admin
 <StringArray>
['not_in_universe', 'no', 'yes']
Length: 3, dtype: str

income
 <StringArray>
['_50000.', 'low_income', nan, '50000+.', '<=50000', 'high_income', '>50000']
Length: 7, dtype: str

source_split
 <StringArray>
['train', nan, 'training', 'test', 'testing']
Length: 5, dtype: str

In [40]:
replacements_dict = {
#class_of_worker 
    'self-employed-not-inc' : 'self_employed_not_incorporated',
    'self_employed_not_inc' : 'self_employed_not_incorporated',
    'not_in_universe' : np.nan,
#education
    'bachelors' : 'bachelors_degree(ba_ab_bs)',
    "bachelor's" : 'bachelors_degree(ba_ab_bs)',
    'hs_grad' : 'high_school_graduate',
#marital_stat
    'married-a_f_spouse_present' : 'married_a_f_spouse_present',
#sex 
    'm' : 'male',
    'f' : 'female',
#detailed_household_and_family_stat 
    'other_rel_<18_never_married_rp_of_subfamily' : 'other_rel_<18_never_marr_rp_of_subfamily',
#detailed_household_summary_in_household 
    'child_under_18_ever_married' : 'child_under_18_never_married',
#live_in_this_house_1_year_ago 
    'not_in_universe_under_1_year_old': 'no',
#country_of_birth_father 
    'trinadad&tobago' : 'trinidad_and_tobago',
#income 
    '50000+.' : '>50000',
    '_50000.' : '<=50000',
#source_split 
    'training' : 'train',
    'testing' : 'test'
    }

In [41]:
for col in list(dirty.select_dtypes('str').columns):
    dirty[col] = dirty[col].replace(replacements_dict)
    print(col, '\n', dirty[col].unique(), end='\n\n')

class_of_worker
 <StringArray>
[                             nan, 'self_employed_not_incorporated',
                        'private',               'local_government',
             'federal_government',     'self_employed_incorporated',
               'state_government',                   'never_worked',
                    'without_pay']
Length: 9, dtype: str

education
 <StringArray>
[                  'high_school_graduate',
             'some_college_but_no_degree',
                             '10th_grade',
                               'children',
             'bachelors_degree(ba_ab_bs)',
                                      nan,
 'masters_degree(ma_ms_meng_med_msw_mba)',
                    'less_than_1st_grade',
     'associates_degree_academic_program',
                      '7th_and_8th_grade',
                  '12th_grade_no_diploma',
    'associates_degree_occup_/vocational',
 'prof_school_degree_(md_dds_dvm_llb_jd)',
                       '5th_or_6th_grade',
                             '11th_grade',
              'doctorate_degree(phd_edd)',
                              '9th_grade',
               '1st_2nd_3rd_or_4th_grade']
Length: 18, dtype: str

enroll_in_edu_inst_last_wk
 <StringArray>
[nan, 'high_school', 'college_or_university']
Length: 3, dtype: str

marital_stat
 <StringArray>
[                        'widowed',                        'divorced',
                   'never_married',                               nan,
 'married_civilian_spouse_present',                       'separated',
           'married_spouse_absent',      'married_a_f_spouse_present']
Length: 8, dtype: str

major_industry_code
 <StringArray>
[        'not_in_universe_or_children',                        'construction',
                                   nan,                       'entertainment',
   'finance_insurance_and_real_estate',                           'education',
        'business_and_repair_services',      'manufacturing_nondurable_goods',
 'personal_services_except_private_hh',         'manufacturing_durable_goods',
         'other_professional_services',                              'mining',
                      'transportation',                     'wholesale_trade',
               'public_administration',                        'retail_trade',
                     'social_services',          'private_household_services',
     'utilities_and_sanitary_services',                      'communications',
                   'hospital_services',             'medical_except_hospital',
                         'agriculture',              'forestry_and_fisheries',
                        'armed_forces']
Length: 25, dtype: str

major_occupation_code
 <StringArray>
[                                    nan,
   'precision_production_craft_&_repair',
                'professional_specialty',
        'executive_admin_and_managerial',
           'handlers_equip_cleaners_etc',
        'adm_support_including_clerical',
 'machine_operators_assmblrs_&_inspctrs',
                         'other_service',
                                 'sales',
            'private_household_services',
       'technicians_and_related_support',
    'transportation_and_material_moving',
          'farming_forestry_and_fishing',
                   'protective_services',
                          'armed_forces']
Length: 15, dtype: str

race
 <StringArray>
[                      'white',   'asian_or_pacific_islander',
 'amer_indian_aleut_or_eskimo',                       'black',
                       'other',                           nan]
Length: 6, dtype: str

hispanic_origin
 <StringArray>
[                'all_other',               'do_not_know',
 'central_or_south_american',        'mexican_(mexicano)',
          'mexican_american',             'other_spanish',
              'puerto_rican',                     'cuban',
                   'chicano',                        'na']
Length: 10, dtype: str

sex
 <StringArray>
['female', nan, 'male']
Length: 3, dtype: str

member_of_a_labor_union
 <StringArray>
[nan, 'no', 'yes']
Length: 3, dtype: str

reason_for_unemployment
 <StringArray>
[                  nan, 'job_loser_on_layoff',     'other_job_loser',
         'new_entrant',          're_entrant',          'job_leaver']
Length: 6, dtype: str

full_or_part_time_employment_stat
 <StringArray>
[                'not_in_labor_force',           'children_or_armed_forces',
                'full_time_schedules',               'unemployed_full_time',
               'unemployed_part_time', 'pt_for_non_econ_reasons_usually_ft',
     'pt_for_econ_reasons_usually_pt',     'pt_for_econ_reasons_usually_ft']
Length: 8, dtype: str

tax_filer_stat
 <StringArray>
[                    'nonfiler',            'head_of_household',
          'joint_both_under_65',                       'single',
                            nan,               'joint_both_65+',
 'joint_one_under_65_&_one_65+']
Length: 7, dtype: str

region_of_previous_residence
 <StringArray>
[nan, 'south', 'northeast', 'midwest', 'west', 'abroad']
Length: 6, dtype: str

state_of_previous_residence
 <StringArray>
[                   nan,             'arkansas',                 'utah',
             'michigan',            'minnesota',               'alaska',
               'kansas',              'indiana',        'massachusetts',
           'new_mexico',               'nevada',            'tennessee',
             'colorado',               'abroad',             'kentucky',
           'california',              'arizona',       'north_carolina',
          'connecticut',              'florida',              'vermont',
             'maryland',             'oklahoma',               'oregon',
                 'ohio',       'south_carolina',                'texas',
              'montana',              'wyoming',              'georgia',
         'pennsylvania',                 'iowa',        'new_hampshire',
             'missouri',              'alabama',         'north_dakota',
           'new_jersey',            'louisiana',        'west_virginia',
             'delaware',             'illinois',                'maine',
            'wisconsin',             'new_york',                'idaho',
 'district_of_columbia',         'south_dakota',             'nebraska',
             'virginia',          'mississippi']
Length: 50, dtype: str

detailed_household_and_family_stat
 <StringArray>
[       'other_rel_18+_ever_marr_not_in_subfamily',
                                     'householder',
         'child_18+_never_marr_not_in_a_subfamily',
           'child_<18_never_marr_not_in_subfamily',
                           'spouse_of_householder',
                            'secondary_individual',
       'other_rel_18+_never_marr_not_in_subfamily',
                           'nonfamily_householder',
      'grandchild_<18_never_marr_not_in_subfamily',
 'grandchild_<18_never_marr_child_of_subfamily_rp',
          'child_18+_ever_marr_not_in_a_subfamily',
            'child_18+_never_marr_rp_of_subfamily',
                'child_18+_spouse_of_subfamily_rp',
  'other_rel_<18_never_marr_child_of_subfamily_rp',
         'child_under_18_of_rp_of_unrel_subfamily',
      'grandchild_18+_never_marr_not_in_subfamily',
             'child_18+_ever_marr_rp_of_subfamily',
         'other_rel_18+_ever_marr_rp_of_subfamily',
                       'rp_of_unrelated_subfamily',
            'other_rel_18+_spouse_of_subfamily_rp',
       'other_rel_<18_never_marr_not_in_subfamily',
            'other_rel_<18_spouse_of_subfamily_rp',
                               'in_group_quarters',
           'grandchild_18+_spouse_of_subfamily_rp',
        'other_rel_18+_never_marr_rp_of_subfamily',
            'child_<18_never_marr_rp_of_subfamily',
            'child_<18_ever_marr_not_in_subfamily',
         'other_rel_<18_ever_marr_rp_of_subfamily',
       'grandchild_18+_ever_marr_not_in_subfamily',
                'child_<18_spouse_of_subfamily_rp',
             'spouse_of_rp_of_unrelated_subfamily',
        'other_rel_<18_never_marr_rp_of_subfamily',
       'grandchild_18+_never_marr_rp_of_subfamily',
        'grandchild_18+_ever_marr_rp_of_subfamily',
             'child_<18_ever_marr_rp_of_subfamily',
        'other_rel_<18_ever_marr_not_in_subfamily',
       'grandchild_<18_never_marr_rp_of_subfamily',
       'grandchild_<18_ever_marr_not_in_subfamily']
Length: 38, dtype: str

detailed_household_summary_in_household
 <StringArray>
[      'other_relative_of_householder',                         'householder',
                   'child_18_or_older',        'child_under_18_never_married',
               'spouse_of_householder',          'nonrelative_of_householder',
 'group_quarters_secondary_individual']
Length: 7, dtype: str

migration_code_change_in_msa
 <StringArray>
[               nan,       'msa_to_msa',         'nonmover',
 'nonmsa_to_nonmsa', 'not_identifiable',    'abroad_to_msa',
    'msa_to_nonmsa', 'abroad_to_nonmsa',    'nonmsa_to_msa']
Length: 9, dtype: str

migration_code_change_in_reg
 <StringArray>
[                             nan,                    'same_county',
                       'nonmover',               'different_region',
    'different_county_same_state', 'different_division_same_region',
                         'abroad',  'different_state_same_division']
Length: 8, dtype: str

migration_code_move_within_reg
 <StringArray>
[                           nan,                  'same_county',
                     'nonmover',     'different_state_in_south',
  'different_county_same_state', 'different_state_in_northeast',
                       'abroad',   'different_state_in_midwest',
      'different_state_in_west']
Length: 9, dtype: str

live_in_this_house_1_year_ago
 <StringArray>
['no', 'yes']
Length: 2, dtype: str

migration_prev_res_in_sunbelt
 <StringArray>
[nan, 'yes', 'no']
Length: 3, dtype: str

family_members_under_18
 <StringArray>
[                     nan,   'both_parents_present',    'mother_only_present',
 'neither_parent_present',    'father_only_present']
Length: 5, dtype: str

country_of_birth_father
 <StringArray>
[               'united_states',                      'vietnam',
                  'philippines',                            nan,
                     'columbia',                      'germany',
                       'mexico',                        'japan',
                         'peru',           'dominican_republic',
                  'south_korea',                         'cuba',
                  'el_salvador',                       'canada',
                     'scotland', 'outlying_u_s_(guam_usvi_etc)',
                        'italy',                    'guatemala',
                      'ecuador',                  'puerto_rico',
                     'cambodia',                        'china',
                       'poland',                    'nicaragua',
                       'taiwan',                      'england',
                      'ireland',                      'hungary',
                   'yugoslavia',          'trinidad_and_tobago',
                      'jamaica',                     'honduras',
                     'portugal',                         'iran',
                       'france',                        'india',
                    'hong_kong',                        'haiti',
                       'greece',           'holand_netherlands',
                     'thailand',                         'laos',
                       'panama']
Length: 43, dtype: str

country_of_birth_mother
 <StringArray>
[               'united_states',                      'vietnam',
                            nan,                     'columbia',
                       'mexico',                  'el_salvador',
                         'peru',                  'puerto_rico',
                         'cuba',                  'philippines',
           'dominican_republic',                      'germany',
                      'england',                    'guatemala',
                     'scotland',                     'portugal',
                        'italy',                      'ecuador',
                   'yugoslavia',                        'china',
                       'poland',                      'hungary',
                    'nicaragua',                       'taiwan',
                      'ireland',                       'canada',
                  'south_korea',          'trinidad_and_tobago',
                      'jamaica',                     'honduras',
                         'iran',                       'france',
                     'cambodia',                        'india',
                    'hong_kong',                        'haiti',
                        'japan',                       'greece',
           'holand_netherlands',                     'thailand',
                       'panama',                         'laos',
 'outlying_u_s_(guam_usvi_etc)']
Length: 43, dtype: str

country_of_birth_self
 <StringArray>
[               'united_states',                      'vietnam',
                            nan,                     'columbia',
                       'mexico',                         'peru',
                         'cuba',                  'philippines',
           'dominican_republic',                  'el_salvador',
                       'canada',                     'scotland',
                     'portugal',                    'guatemala',
                      'ecuador',                      'germany',
 'outlying_u_s_(guam_usvi_etc)',                  'puerto_rico',
                        'italy',                        'china',
                       'poland',                    'nicaragua',
                       'taiwan',                      'england',
                      'ireland',                  'south_korea',
          'trinidad_and_tobago',                      'jamaica',
                     'honduras',                         'iran',
                      'hungary',                       'france',
                     'cambodia',                        'india',
                    'hong_kong',                        'japan',
                        'haiti',           'holand_netherlands',
                       'greece',                     'thailand',
                       'panama',                   'yugoslavia',
                         'laos']
Length: 43, dtype: str

citizenship
 <StringArray>
[          'native_born_in_the_united_states',
          'foreign_born_not_a_citizen_of_u_s',
                                          nan,
 'foreign_born_u_s_citizen_by_naturalization',
   'native_born_abroad_of_american_parent(s)',
 'native_born_in_puerto_rico_or_u_s_outlying']
Length: 6, dtype: str

fill_inc_questionnaire_for_veteran_admin
 <StringArray>
[nan, 'no', 'yes']
Length: 3, dtype: str

income
 <StringArray>
['<=50000', 'low_income', nan, '>50000', 'high_income']
Length: 5, dtype: str

source_split
 <StringArray>
['train', nan, 'test']
Length: 3, dtype: str

In [42]:
(dirty.select_dtypes('str').isna().sum()/len(dirty)*100).sort_values(ascending=False)

fill_inc_questionnaire_for_veteran_admin    98.993946
reason_for_unemployment                     96.989188
enroll_in_edu_inst_last_wk                  93.678664
state_of_previous_residence                 92.505546
region_of_previous_residence                92.158723
migration_prev_res_in_sunbelt               92.158723
member_of_a_labor_union                     90.463032
family_members_under_18                     72.381452
class_of_worker                             51.217556
migration_code_move_within_reg              50.748109
migration_code_change_in_msa                50.748109
migration_code_change_in_reg                50.748109
major_occupation_code                       50.442717
country_of_birth_father                      3.388709
country_of_birth_mother                      3.070955
sex                                          2.000080
race                                         1.999746
income                                       1.999746
marital_stat                                 1.999746
education                                    1.999746
major_industry_code                          1.999746
tax_filer_stat                               1.999746
source_split                                 1.999746
citizenship                                  1.999746
country_of_birth_self                        1.723089
hispanic_origin                              0.000000
full_or_part_time_employment_stat            0.000000
live_in_this_house_1_year_ago                0.000000
detailed_household_and_family_stat           0.000000
detailed_household_summary_in_household      0.000000
dtype: float64

In [43]:
dirty.select_dtypes('str').fillna('no_information')

,class_of_worker,education,enroll_in_edu_inst_last_wk,marital_stat,major_industry_code,major_occupation_code,race,hispanic_origin,sex,member_of_a_labor_union,...,live_in_this_house_1_year_ago,migration_prev_res_in_sunbelt,family_members_under_18,country_of_birth_father,country_of_birth_mother,country_of_birth_self,citizenship,fill_inc_questionnaire_for_veteran_admin,income,source_split
0,no_information,high_school_graduate,no_information,widowed,not_in_universe_or_children,no_information,white,all_other,female,no_information,...,no,no_information,no_information,united_states,united_states,united_states,native_born_in_the_united_states,no_information,<=50000,train
1,self_employed_not_incorporated,some_college_but_no_degree,no_information,divorced,construction,precision_production_craft_&_repair,white,all_other,no_information,no_information,...,no,yes,no_information,united_states,united_states,united_states,native_born_in_the_united_states,no_information,<=50000,train
2,no_information,10th_grade,high_school,never_married,not_in_universe_or_children,no_information,asian_or_pacific_islander,all_other,female,no_information,...,no,no_information,no_information,vietnam,vietnam,vietnam,foreign_born_not_a_citizen_of_u_s,no_information,<=50000,train
3,no_information,children,no_information,never_married,not_in_universe_or_children,no_information,white,all_other,female,no_information,...,yes,no_information,both_parents_present,united_states,united_states,united_states,native_born_in_the_united_states,no_information,<=50000,train
4,no_information,children,no_information,no_information,no_information,no_information,white,all_other,female,no_information,...,yes,no_information,both_parents_present,united_states,united_states,united_states,native_born_in_the_united_states,no_information,<=50000,train
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299283,private,bachelors_degree(ba_ab_bs),no_information,married_civilian_spouse_present,other_professional_services,executive_admin_and_managerial,white,all_other,female,no_information,...,no,no_information,no_information,united_states,united_states,united_states,native_born_in_the_united_states,no_information,<=50000,test
299284,no_information,9th_grade,no_information,married_civilian_spouse_present,not_in_universe_or_children,no_information,white,all_other,male,no_information,...,yes,no_information,no_information,united_states,united_states,united_states,native_born_in_the_united_states,no_information,<=50000,test
299285,no_information,high_school_graduate,no_information,widowed,not_in_universe_or_children,no_information,white,all_other,female,no_information,...,no,no_information,no_information,united_states,united_states,united_states,native_born_in_the_united_states,no_information,<=50000,train
299286,self_employed_not_incorporated,some_college_but_no_degree,no_information,divorced,construction,precision_production_craft_&_repair,white,all_other,no_information,no_information,...,no,yes,no_information,united_states,united_states,united_states,native_born_in_the_united_states,no_information,<=50000,train
299287,no_information,10th_grade,high_school,never_married,not_in_universe_or_children,no_information,asian_or_pacific_islander,all_other,female,no_information,...,no,no_information,no_information,vietnam,vietnam,vietnam,foreign_born_not_a_citizen_of_u_s,no_information,<=50000,train

#### Missing Values

In [44]:
(dirty.select_dtypes('str').isna().sum()/len(dirty)*100).sort_values(ascending=False)

fill_inc_questionnaire_for_veteran_admin    98.993946
reason_for_unemployment                     96.989188
enroll_in_edu_inst_last_wk                  93.678664
state_of_previous_residence                 92.505546
region_of_previous_residence                92.158723
migration_prev_res_in_sunbelt               92.158723
member_of_a_labor_union                     90.463032
family_members_under_18                     72.381452
class_of_worker                             51.217556
migration_code_move_within_reg              50.748109
migration_code_change_in_msa                50.748109
migration_code_change_in_reg                50.748109
major_occupation_code                       50.442717
country_of_birth_father                      3.388709
country_of_birth_mother                      3.070955
sex                                          2.000080
race                                         1.999746
income                                       1.999746
marital_stat                                 1.999746
education                                    1.999746
major_industry_code                          1.999746
tax_filer_stat                               1.999746
source_split                                 1.999746
citizenship                                  1.999746
country_of_birth_self                        1.723089
hispanic_origin                              0.000000
full_or_part_time_employment_stat            0.000000
live_in_this_house_1_year_ago                0.000000
detailed_household_and_family_stat           0.000000
detailed_household_summary_in_household      0.000000
dtype: float64

In [45]:
for col in dirty.select_dtypes('str').columns:
    dirty[col] = dirty[col].fillna('no_information')

In [46]:
(dirty.select_dtypes('str').isna().sum()/len(dirty)*100).sort_values(ascending=False)

class_of_worker                             0.0
education                                   0.0
enroll_in_edu_inst_last_wk                  0.0
marital_stat                                0.0
major_industry_code                         0.0
major_occupation_code                       0.0
race                                        0.0
hispanic_origin                             0.0
sex                                         0.0
member_of_a_labor_union                     0.0
reason_for_unemployment                     0.0
full_or_part_time_employment_stat           0.0
tax_filer_stat                              0.0
region_of_previous_residence                0.0
state_of_previous_residence                 0.0
detailed_household_and_family_stat          0.0
detailed_household_summary_in_household     0.0
migration_code_change_in_msa                0.0
migration_code_change_in_reg                0.0
migration_code_move_within_reg              0.0
live_in_this_house_1_year_ago               0.0
migration_prev_res_in_sunbelt               0.0
family_members_under_18                     0.0
country_of_birth_father                     0.0
country_of_birth_mother                     0.0
country_of_birth_self                       0.0
citizenship                                 0.0
fill_inc_questionnaire_for_veteran_admin    0.0
income                                      0.0
source_split                                0.0
dtype: float64

### 2.3 Numerical columns

In [47]:
dirty.select_dtypes('number').describe()

,age,detailed_industry_recode,detailed_occupation_recode,wage_per_hour,capital_gains,capital_losses,dividends_from_stocks,instance_weight,num_persons_worked_for_employer,own_business_or_self_employed,veterans_benefits,weeks_worked_in_year,year
count,292203.000000,293303.000000,299288.000000,298166.000000,298166.000000,299288.000000,299288.000000,299288.000000,299288.000000,299288.000000,299288.000000,298166.000000,299288.000000
mean,34.542554,15.348486,11.314744,55.098080,431.301010,36.848641,195.849296,1740.096197,1.956156,0.176459,1.516502,23.179578,94.506469
std,22.329121,18.054087,14.455996,273.413379,4667.560456,269.788444,1937.837469,994.141051,2.364851,0.555238,0.850392,24.404981,3.573081
min,-2.000000,0.000000,0.000000,-100.000000,0.000000,0.000000,0.000000,37.870000,0.000000,0.000000,0.000000,0.000000,94.000000
25%,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1060.490000,0.000000,0.000000,2.000000,0.000000,94.000000
50%,33.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1617.100000,1.000000,0.000000,2.000000,8.000000,95.000000
75%,50.000000,33.000000,26.000000,0.000000,0.000000,0.000000,0.000000,2188.110000,4.000000,0.000000,2.000000,52.000000,95.000000
max,150.000000,51.000000,46.000000,9999.000000,99999.000000,4608.000000,99999.000000,18656.300000,6.000000,2.000000,2.000000,80.000000,2030.000000

In [48]:
(dirty.select_dtypes('number').isna().sum()/len(dirty)*100).sort_values(ascending=False)

age                                2.367285
detailed_industry_recode           1.999746
wage_per_hour                      0.374890
capital_gains                      0.374890
weeks_worked_in_year               0.374890
detailed_occupation_recode         0.000000
capital_losses                     0.000000
instance_weight                    0.000000
dividends_from_stocks              0.000000
num_persons_worked_for_employer    0.000000
own_business_or_self_employed      0.000000
veterans_benefits                  0.000000
year                               0.000000
dtype: float64

In [49]:
for col in dirty.select_dtypes('number').columns:
    dirty[col] = dirty[col].fillna(dirty[col].median())

In [50]:
(dirty.select_dtypes('number').isna().sum()/len(dirty)*100).sort_values(ascending=False)

age                                0.0
detailed_industry_recode           0.0
detailed_occupation_recode         0.0
wage_per_hour                      0.0
capital_gains                      0.0
capital_losses                     0.0
dividends_from_stocks              0.0
instance_weight                    0.0
num_persons_worked_for_employer    0.0
own_business_or_self_employed      0.0
veterans_benefits                  0.0
weeks_worked_in_year               0.0
year                               0.0
dtype: float64

In [51]:
pd.DataFrame.to_csv(dirty, path + 'clean/census_income_kdd_clean.csv')